spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-api
            uri: lb://order-api #
            predicates:
               - Path=/shop/**
          - id: product-api
            uri: lb://product-api
            predicates:
              - Path=/products/**
          - id: coupon-api
            uri: lb://coupon-api
            predicates:
              - Path=/coupons/**
          - id: user-api
            uri: lb://user-api
            predicates:
              - Path=/users/**